"""cambie configuracion correo

Revision ID: 40023ef22095
Revises: 15add0c67b7d
Create Date: 2025-07-25 00:36:14.686473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40023ef22095'
down_revision = '15add0c67b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('correo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('correo'), ['correo'], unique=True)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
