"""agrege columna

Revision ID: 82f33268543e
Revises: d45f7cade019
Create Date: 2025-07-28 02:58:30.137200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82f33268543e'
down_revision = 'd45f7cade019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=True))
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
